import { createClient } from '@/lib/supabase/client'
import { getImageModel } from './client'
import { enhanceImagePrompt, ImageStyle } from './prompts'
import { logger } from '@/lib/logging/logger'

/**
 * Generate image using Google Gemini 2.5 Flash Image Preview
 * Uses the official Gemini image generation API
 *
 * @param prompt - Detailed image generation prompt
 * @param businessProfileId - Business profile ID for file organization
 * @param style - Optional style preset (photorealistic, illustration, minimalist, product, lifestyle)
 * @returns Supabase Storage public URL for the generated image
 */
export async function generateImage(
  prompt: string,
  businessProfileId: string,
  style: ImageStyle = 'photorealistic'
): Promise<string> {
  const startTime = Date.now()

  try {
    logger.info('Generating AI image with Gemini 2.5 Flash', {
      businessProfileId,
      promptLength: prompt.length,
      style,
    })

    // Enhance prompt with style-specific details
    // Following Google's guideline: "Describe the scene, don't just list keywords"
    const enhancedPrompt = enhanceImagePrompt(prompt, style)

    // Call Gemini 2.5 Flash Image Preview API
    const model = getImageModel()
    const result = await model.generateContent([enhancedPrompt])

    // Extract image data from response
    // Response structure: response.candidates[0].content.parts[0].inline_data
    const response = result.response
    const candidates = response.candidates

    if (!candidates || candidates.length === 0) {
      throw new Error('No image generated by Gemini API')
    }

    const parts = candidates[0].content.parts
    if (!parts || parts.length === 0) {
      throw new Error('No content parts in Gemini API response')
    }

    // Find the part with inline_data (binary image)
    const imagePart = parts.find((part: any) => part.inlineData)
    if (!imagePart || !imagePart.inlineData) {
      throw new Error('No inline_data found in Gemini API response')
    }

    // Get binary image data and MIME type
    const { data: base64Data, mimeType } = imagePart.inlineData

    // Convert base64 to buffer for upload
    const imageBuffer = Buffer.from(base64Data, 'base64')

    // Determine file extension from MIME type
    const extension = mimeType === 'image/png' ? 'png' : 'jpeg'

    // Generate unique filename
    const timestamp = Date.now()
    const filename = `generated-images/${businessProfileId}/${timestamp}.${extension}`

    // Upload to Supabase Storage
    const supabase = createClient()
    const { error } = await supabase.storage.from('post-images').upload(filename, imageBuffer, {
      contentType: mimeType,
      cacheControl: '3600',
      upsert: false,
    })

    if (error) {
      logger.error('Failed to upload generated image', {
        businessProfileId,
        error: error.message,
      })
      throw new Error(`Failed to upload generated image: ${error.message}`)
    }

    // Get public URL
    const {
      data: { publicUrl },
    } = supabase.storage.from('post-images').getPublicUrl(filename)

    const duration = Date.now() - startTime

    logger.info('Successfully generated and uploaded image', {
      businessProfileId,
      filename,
      mimeType,
      sizeBytes: imageBuffer.length,
      durationMs: duration,
    })

    return publicUrl
  } catch (error) {
    const duration = Date.now() - startTime

    logger.error('Image generation failed', {
      businessProfileId,
      error: error instanceof Error ? error.message : 'Unknown error',
      durationMs: duration,
    })

    throw new Error('Failed to generate image')
  }
}

/**
 * Upload existing image file to Supabase Storage
 * Used when user uploads their own image
 *
 * @param file - Image file (jpeg, png, webp)
 * @param businessProfileId - Business profile ID for file organization
 * @returns Supabase Storage public URL
 */
export async function uploadImage(file: File, businessProfileId: string): Promise<string> {
  // Validate file type
  const allowedTypes = ['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml']
  if (!allowedTypes.includes(file.type)) {
    throw new Error('Invalid file type. Allowed types: JPEG, PNG, WebP, SVG')
  }

  // Validate file size (max 10MB)
  const maxSize = 10 * 1024 * 1024 // 10MB
  if (file.size > maxSize) {
    throw new Error('File size exceeds 10MB limit')
  }

  // Generate unique filename
  const timestamp = Date.now()
  const extension = file.name.split('.').pop()
  const filename = `uploads/${businessProfileId}/${timestamp}.${extension}`

  // Upload to Supabase Storage
  const supabase = createClient()
  const { error } = await supabase.storage.from('post-images').upload(filename, file, {
    contentType: file.type,
    cacheControl: '3600',
    upsert: false,
  })

  if (error) {
    console.error('Supabase Storage upload error:', error)
    throw new Error('Failed to upload image')
  }

  // Get public URL
  const {
    data: { publicUrl },
  } = supabase.storage.from('post-images').getPublicUrl(filename)

  return publicUrl
}

/**
 * Delete image from Supabase Storage
 * Used when post is deleted or image is replaced
 *
 * @param imageUrl - Full Supabase Storage URL
 */
export async function deleteImage(imageUrl: string): Promise<void> {
  try {
    // Extract filename from URL
    const url = new URL(imageUrl)
    const pathParts = url.pathname.split('/post-images/')
    if (pathParts.length < 2) {
      throw new Error('Invalid image URL')
    }
    const filename = pathParts[1]

    const supabase = createClient()
    const { error } = await supabase.storage.from('post-images').remove([filename])

    if (error) {
      console.error('Supabase Storage delete error:', error)
      throw new Error('Failed to delete image')
    }
  } catch (error) {
    console.error('Image deletion error:', error)
    // Don't throw error - deletion failure shouldn't block other operations
    console.warn('Image deletion failed, but continuing...')
  }
}
